name: foody
description: >-
  Foody App, resturant manager or food delivery network
homepage: 'https://moughamir.github.io/show/foody'
repository: 'https://github.com/omnizya/foody'
issue_tracker: 'https://github.com/omnizya/foody/issues'
documentation: 'https://moughamir.github.io/docs/foody'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter:
  uses-material-design: true
  assets:
    - assets/pictures/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
    - family: RalewayLight
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
    - family: RalewayMedium
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
